// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUEEEmJDF1_6bMq3a0UtRlkdIaBx8Euzo',
    appId: '1:924503561966:web:21d5fe50e57d4f5df345ff',
    messagingSenderId: '924503561966',
    projectId: 'iskomed-7d7b4',
    authDomain: 'iskomed-7d7b4.firebaseapp.com',
    storageBucket: 'iskomed-7d7b4.appspot.com',
    measurementId: 'G-ZD1RJY5L2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmVkOSQfgDKY9GPdJi0ydaKraaQJT17t4',
    appId: '1:924503561966:android:24905f26e241e522f345ff',
    messagingSenderId: '924503561966',
    projectId: 'iskomed-7d7b4',
    storageBucket: 'iskomed-7d7b4.appspot.com',
  );
}
